---
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
    dev: png
    keep_md: yes
  word_document:
    toc: TRUE
    toc_depth: 2
  pdf_document:
    toc: TRUE
    toc_depth: 2
    dev: png
    extra_dependencies: ["float"]
    keep_md: yes
urlcolor: blue
params:
  managedarea: ma,
  p_inc: included_params,
  a_inc: included_acts,
  d_inc: included_depths
title: '`r paste(ma)`'
subtitle: '`r paste("SEACAR Discrete Water Quality Analysis")`'
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(
   warning=FALSE,
   message=FALSE,
   echo=FALSE,
   dpi=200
)
```


```{r libraries, message=FALSE, echo=FALSE, warning=FALSE, include=FALSE}
library(knitr)
library(data.table)
library(dplyr)
library(lubridate)
library(ggplot2)
library(ggpubr)
library(scales)
library(EnvStats)
library(tidyr)
library(kableExtra)
library(glue)
library(grid)
options(scipen=999)
```



# Parameters



``` {r load_data_table function}

# Load Data Table Function
load_data_table <- function(p, a="All", d="All", table) {
  
  # Declaring RDS file list of respective tables
  files <- list.files(here::here("output/tables"),pattern = "\\.rds$")
  
  if (table == "data") {
    filename_string <- paste0(p,"_",table)
  } else {
    filename_string <- paste0(p,"_",a,"_",d,"_",table)
  }
  
  # subset file list to select desired table RDS file
  table_file <- paste0("output/tables/",str_subset(files, filename_string))
  
  # importing RDS files
  df <- lapply(table_file, readRDS)

  return(df)
}


```



```{r data_exclusion_table function}
data_exclusion_table <- function(data, parameter) {
  # Creates ResultTable to display statistics below plot
  data_excluded <- data %>% 
    filter(Use_In_Analysis==FALSE & ManagedAreaName==ma) %>%
    select(ProgramID, ProgramLocationID, SampleDate, ResultValue, SEACAR_QAQCFlagCode, Include, SufficientData) %>%
    arrange(SampleDate)
  
  if (nrow(data_excluded) > 0) {
    cat("\n\n\\pagebreak\n")
    # cat("Excluded data for ", parameter)
    # t1 <- ggtexttable(data_excluded, rows=NULL,
    #                   theme = ttheme(base_size=10)) %>%
    #   tab_add_footnote(text="Additional info here. Excluded Values etc.",
    #                    size=10, face="italic")
    # print(t1)
    
    data_table <- kable(data_excluded, 
                        format="simple", 
                        col.names = c("ProgramID", "ProgramLocationID", "SampleDate", "Value", 
                                      "QAQCFlagCode", "Include", "SufficientData"), 
                        caption=paste0("Excluded values for ", parameter)) %>%
      kable_styling(latex_options="scale_down",
                    position = "center")
    
    print(data_table)
    cat("\n \n \n")
  }
}

```



```{r Trendlines_ManagedArea Function}

plot_trendlines <- function(p, a, d, activity_label, depth_label, y_labels, parameter) {
  
  MA_YM_Stats <- as.data.frame(load_data_table(p, a, d, "MA_MMYY_Stats"))
  skt_stats <- as.data.frame(load_data_table(p, a, d, "skt_stats"))
  
  ### SKT STATS ###
  # Gets x and y values for starting point for trendline
  KT.Plot <- skt_stats %>%
    group_by(ManagedAreaName) %>%
    summarize(x=decimal_date(EarliestSampleDate),
              y=(x-EarliestYear)*SennSlope+SennIntercept)
  # Gets x and y values for ending point for trendline
  KT.Plot2 <- skt_stats %>%
    group_by(ManagedAreaName) %>%
    summarize(x=decimal_date(LastSampleDate),
              y=(x-EarliestYear)*SennSlope+SennIntercept)
  # Combines the starting and endpoints for plotting the trendline
  KT.Plot <- bind_rows(KT.Plot, KT.Plot2)
  rm(KT.Plot2)
  KT.Plot <- as.data.table(KT.Plot[order(KT.Plot$ManagedAreaName), ])
  KT.Plot <- KT.Plot[!is.na(KT.Plot$y),]

  # Checking for missing values
  check_ym <- MA_YM_Stats %>%
    filter(ManagedAreaName == ma)
  
  if (nrow(check_ym) == 0) {
    invisible()
    # print("error")
  } else {
    # Gets data to be used in plot for managed area
    plot_data <- MA_YM_Stats[MA_YM_Stats$ManagedAreaName==ma,]

    # Gets trendline data for managed area
    KT.plot_data <- KT.Plot[KT.Plot$ManagedAreaName==ma,]

    #Determine max and min time (Year) for plot x-axis
    t_min <- min(plot_data$Year)
    t_max <- max(plot_data$YearMonthDec)
    t_max_brk <- as.integer(round(t_max, 0))
    t <- t_max-t_min
    min_RV <- min(plot_data$Mean)

    # Sets break intervals based on the number of years spanned by data
    if(t>=30){
      brk <- -10
    }else if(t<30 & t>=10){
      brk <- -5
    }else if(t<10 & t>=4){
      brk <- -2
    }else if(t<4){
      brk <- -1
    }

    # Create plot object with data and trendline
    p1 <- ggplot(data=plot_data,
          aes(x=YearMonthDec, y=Mean)) +
      # geom_line(size=0.75, color="#333333", alpha=0.6) +
      geom_point(shape=21, size=3, color="#333333", fill="#cccccc",
           alpha=0.75) +
      geom_line(data=KT.plot_data, aes(x=x, y=y),
          color="#000099", size=1.2, alpha=0.7) +
      labs(title=paste0(parameter,", ",activity_label, ", ",depth_label),
        subtitle=ma,
        x="Year", y=y_labels) +
      scale_x_continuous(limits=c(t_min-0.25, t_max+0.25),
                breaks=seq(t_max_brk, t_min, brk)) +
      plot_theme
    # Creates ResultTable to display statistics below plot
    ResultTable <- skt_stats[skt_stats$ManagedAreaName==ma, ] %>%
      select(RelativeDepth, N_Data, N_Years, Median, Independent, tau, p,
          SennSlope, SennIntercept, ChiSquared, pChiSquared, Trend)
    # Create table object
    t1 <- ggtexttable(ResultTable, rows=NULL,
            theme=ttheme(base_size=10)) %>%
      tab_add_footnote(text="p < 0.00005 appear as 0 due to rounding.\n
              SennIntercept is intercept value at beginning of
              record for monitoring location",
              size=10, face="italic")
    # Arrange and display plot and statistic table
    print(ggarrange(p1, t1, ncol=1, heights=c(0.85, 0.15)))
    # Add extra space at the end to prevent the next figure from being too
    # close.
    cat("\n \n \n")
    rm(plot_data)
    rm(MA_YM_Stats)
    # rm(KT.Plot)
    rm(skt_stats)
  }
}

```



```{r plot_boxplots_function, eval = FALSE}

plot_boxplots <- function(p, a, d, activity_label, depth_label, y_labels, parameter, data) {
  # data <- as.data.frame(load_data_table(p, a, d, "data"))
  
  plot_title <- paste0(parameter,", ",activity_label, ", ",depth_label)
  
  # Determine upper and lower bounds of time for x-axis
  plot_data <- data[data$SufficientData==TRUE &
             data$ManagedAreaName==ma,]
  year_lower <- min(plot_data$Year)
  year_upper <- max(plot_data$Year)
  
  # Determine upper and lower bounds of ResultValue for y-axis
  min_RV <- min(plot_data$ResultValue)
  mn_RV <- mean(plot_data$ResultValue[plot_data$ResultValue <
                      quantile(data$ResultValue, 0.98)])
  sd_RV <- sd(plot_data$ResultValue[plot_data$ResultValue <
                    quantile(data$ResultValue, 0.98)])
  # Sets x- and y-axis scale
  x_scale <- ifelse(year_upper - year_lower > 30, 10, 5)
  y_scale <- mn_RV + 4 * sd_RV
  
  ##Year plots
  # Create plot object for auto-scaled y-axis plot
  p1 <- ggplot(data=plot_data,
        aes(x=Year, y=ResultValue, group=Year)) +
    geom_boxplot(color="#333333", fill="#cccccc", outlier.shape=21,
           outlier.size=3, outlier.color="#333333",
           outlier.fill="#cccccc", outlier.alpha=0.75) +
    labs(subtitle="Autoscale",
      x="Year", y=y_labels) +
    scale_x_continuous(limits=c(year_lower - 1, year_upper + 1),
              breaks=rev(seq(year_upper,
                    year_lower, -x_scale))) +
    plot_theme
  # Create plot object for y-axis scaled plot
  p2 <- ggplot(data=plot_data,
        aes(x=Year, y=ResultValue, group=Year)) +
    geom_boxplot(color="#333333", fill="#cccccc", outlier.shape=21,
           outlier.size=3, outlier.color="#333333",
           outlier.fill="#cccccc", outlier.alpha=0.75) +
    labs(subtitle="Scaled to 4x Standard Deviation",
      x="Year", y=y_labels) +
    ylim(min_RV, y_scale) +
    scale_x_continuous(limits=c(year_lower - 1, year_upper + 1),
              breaks=rev(seq(year_upper,
                    year_lower, -x_scale))) +
    plot_theme
  # Create plot object for y-axis scaled plot for past 10 years
  p3 <- ggplot(data=plot_data[plot_data$Year >= year_upper - 10, ],
        aes(x=Year, y=ResultValue, group=Year)) +
    geom_boxplot(color="#333333", fill="#cccccc", outlier.shape=21,
           outlier.size=3, outlier.color="#333333",
           outlier.fill="#cccccc", outlier.alpha=0.75) +
    labs(subtitle="Scaled to 4x Standard Deviation, Last 10 Years",
      x="Year", y=y_labels) +
    ylim(min_RV, y_scale) +
    scale_x_continuous(limits=c(year_upper - 10.5, year_upper + 1),
              breaks=rev(seq(year_upper, year_upper - 10,-2))) +
    plot_theme
  # Arrange plot objects
  Yset <- ggarrange(p1, p2, p3, ncol=1)
  # Create plot title object
  p0 <- ggplot() + labs(title=plot_title,
              subtitle="By Year") +
    plot_theme + theme(panel.border=element_blank(),
              panel.grid.major=element_blank(),
              panel.grid.minor=element_blank(),
              axis.line=element_blank())
  
  
  ## Year & Month Plots
  # Create plot object for auto-scaled y-axis plot
  p4 <- ggplot(data=plot_data,
        aes(x=YearMonthDec, y=ResultValue,
            group=YearMonth, color=as.factor(Month))) +
    geom_boxplot(fill="#cccccc", outlier.size=1.5, outlier.alpha=0.75) +
    labs(subtitle="Autoscale",
      x="Year", y=y_labels, color="Month") +
    scale_x_continuous(limits=c(year_lower - 1, year_upper + 1),
              breaks=rev(seq(year_upper,
                    year_lower, -x_scale))) +
    plot_theme +
    theme(legend.position="none")
  # Create plot object for y-axis scaled plot
  p5 <- ggplot(data=plot_data,
        aes(x=YearMonthDec, y=ResultValue,
            group=YearMonth, color=as.factor(Month))) +
    geom_boxplot(fill="#cccccc", outlier.size=1.5, outlier.alpha=0.75) +
    labs(subtitle="Scaled to 4x Standard Deviation",
      x="Year", y=y_labels, color="Month") +
    ylim(min_RV, y_scale) +
    scale_x_continuous(limits=c(year_lower - 1, year_upper + 1),
              breaks=rev(seq(year_upper,
                    year_lower, -x_scale))) +
    plot_theme +
    theme(legend.position="top", legend.box="horizontal") +
    guides(color=guide_legend(nrow=1))
  # Create plot object for y-axis scaled plot for past 10 years
  p6 <- ggplot(data=plot_data[plot_data$Year >= year_upper - 10, ],
        aes(x=YearMonthDec, y=ResultValue,
            group=YearMonth, color=as.factor(Month))) +
    geom_boxplot(fill="#cccccc", outlier.size=1.5, outlier.alpha=0.75) +
    labs(subtitle="Scaled to 4x Standard Deviation, Last 10 Years",
      x="Year", y=y_labels, color="Month") +
    ylim(min_RV, y_scale) +
    scale_x_continuous(limits=c(year_upper - 10.5, year_upper + 1),
              breaks=rev(seq(year_upper, year_upper - 10,-2))) +
    plot_theme +
    theme(legend.position="none")
  # Create legend object
  leg1 <- get_legend(p5)
  # Arrange plots and legend
  YMset <- ggarrange(leg1, p4, p5 + theme(legend.position="none"), p6,
           ncol=1, heights=c(0.1, 1, 1, 1))
  # Create plot title object
  p00 <- ggplot() + labs(title=plot_title,
               subtitle="By Year & Month") + plot_theme +
    theme(panel.border=element_blank(),
       panel.grid.major=element_blank(),
       panel.grid.minor=element_blank(), axis.line=element_blank())
  
  ## Month Plots
  # Create plot object for auto-scaled y-axis plot
  p7 <- ggplot(data=plot_data,
        aes(x=Month, y=ResultValue,
            group=Month, fill=as.factor(Month))) +
    geom_boxplot(color="#333333", outlier.shape=21, outlier.size=3,
           outlier.color="#333333", outlier.alpha=0.75) +
    labs(subtitle="Autoscale",
      x="Month", y=y_labels, fill="Month") +
    scale_x_continuous(limits=c(0, 13), breaks=seq(3, 12, 3)) +
    plot_theme +
    theme(legend.position="none")
  # Create plot object for y-axis scaled plot
  p8 <- ggplot(data=plot_data,
        aes(x=Month, y=ResultValue,
            group=Month, fill=as.factor(Month))) +
    geom_boxplot(color="#333333", outlier.shape=21, outlier.size=3,
           outlier.color="#333333", outlier.alpha=0.75) +
    labs(subtitle="Scaled to 4x Standard Deviation",
      x="Month", y=y_labels, fill="Month") +
    ylim(min_RV, y_scale) +
    scale_x_continuous(limits=c(0, 13), breaks=seq(3, 12, 3)) +
    plot_theme +
    theme(legend.position="top", legend.box="horizontal") +
    guides(fill=guide_legend(nrow=1))
  # Create plot object for y-axis scaled plot for past 10 years
  p9 <- ggplot(data=plot_data[plot_data$Year >= year_upper - 10, ],
        aes(x=Month, y=ResultValue,
            group=Month, fill=as.factor(Month))) +
    geom_boxplot(color="#333333", outlier.shape=21, outlier.size=3,
           outlier.color="#333333", outlier.alpha=0.75) +
    labs(subtitle="Scaled to 4x Standard Deviation, Last 10 Years",
      x="Month", y=y_labels, fill="Month") +
    ylim(min_RV, y_scale) +
    scale_x_continuous(limits=c(0, 13), breaks=seq(3, 12, 3)) +
    plot_theme +
    theme(legend.position="none")
  # Create legend object
  leg2 <- get_legend(p8)
  # Arrange plots and legend
  Mset <- ggarrange(leg2, p7, p8 + theme(legend.position="none"), p9,
          ncol=1, heights=c(0.1, 1, 1, 1))
  # Create title object
  p000 <- ggplot() + labs(title=plot_title,
             subtitle="By Month") + plot_theme +
    theme(panel.border=element_blank(),
       panel.grid.major=element_blank(),
       panel.grid.minor=element_blank(), axis.line=element_blank())
  # Arrange and display plots with titles for all combinations
  print(ggarrange(p0, Yset, ncol=1, heights=c(0.07, 1)))
  print(ggarrange(p00, YMset, ncol=1, heights=c(0.07, 1)))
  print(ggarrange(p000, Mset, ncol=1, heights=c(0.07, 1, 0.7)))
  # Add extra space at the end to prevent the next figure from being too
  # close.
  cat("\n \n \n")
  
  rm(plot_data)
  rm(p1, p2, p3, p4, p5, p6, p7, p8, p9, p0, p00, p000, leg1, leg2,
    Yset, YMset, Mset)
}

```



```{r plot_boxplots modified function}

plot_boxplots <- function(p, a, d, activity_label, depth_label, y_labels, parameter, data) {
  # data <- as.data.frame(load_data_table(p, a, d, "data"))
  
  plot_title <- paste0(parameter,", ",activity_label, ", ",depth_label)
  
  # Determine upper and lower bounds of time for x-axis
  plot_data <- data[data$Use_In_Analysis==TRUE &
                      data$ManagedAreaName==ma,]
  year_lower <- min(plot_data$Year)
  year_upper <- max(plot_data$Year)
  
  # Determine upper and lower bounds of ResultValue for y-axis
  min_RV <- min(plot_data$ResultValue)
  mn_RV <- mean(plot_data$ResultValue[plot_data$ResultValue <
                                        quantile(data$ResultValue, 0.98)])
  sd_RV <- sd(plot_data$ResultValue[plot_data$ResultValue <
                                      quantile(data$ResultValue, 0.98)])
  # Sets x- and y-axis scale
  x_scale <- ifelse(year_upper - year_lower > 30, 10, 5)
  y_scale <- mn_RV + 4 * sd_RV
  
  ##Year plots
  # Create plot object for auto-scaled y-axis plot
  p1 <- ggplot(data=plot_data,
               aes(x=Year, y=ResultValue, group=Year)) +
    geom_boxplot(color="#333333", fill="#cccccc", outlier.shape=21,
                 outlier.size=3, outlier.color="#333333",
                 outlier.fill="#cccccc", outlier.alpha=0.75) +
    labs(subtitle="By Year",
         x="Year", y=y_labels) +
    scale_x_continuous(limits=c(year_lower - 1, year_upper + 1),
                       breaks=rev(seq(year_upper,
                                      year_lower, -x_scale))) +
    plot_theme
  
  p4 <- ggplot(data=plot_data,
               aes(x=YearMonthDec, y=ResultValue,
                   group=YearMonth, color=as.factor(Month))) +
    geom_boxplot(fill="#cccccc", outlier.size=1.5, outlier.alpha=0.75) +
    labs(subtitle="By Year and Month",
         x="Year", y=y_labels, color="Month") +
    scale_x_continuous(limits=c(year_lower - 1, year_upper + 1),
                       breaks=rev(seq(year_upper,
                                      year_lower, -x_scale))) +
    plot_theme +
    theme(legend.position="none")
  
  # Month Plots
  # Create plot object for auto-scaled y-axis plot
  p7 <- ggplot(data=plot_data,
               aes(x=Month, y=ResultValue,
                   group=Month, fill=as.factor(Month))) +
    geom_boxplot(color="#333333", outlier.shape=21, outlier.size=3,
                 outlier.color="#333333", outlier.alpha=0.75) +
    labs(subtitle="By Month",
         x="Month", y=y_labels, fill="Month") +
    scale_x_continuous(limits=c(0, 13), breaks=seq(3, 12, 3)) +
    plot_theme +
    theme(legend.position="none",
          axis.text.x=element_text(angle = 0, hjust = 1))
  
  set <- ggarrange(p1 + rremove("ylab"), p4 + rremove("ylab"), p7 + rremove("ylab"), ncol=1)
  
  p0 <- ggplot() + labs(title=plot_title, 
                        subtitle=ma) + 
    plot_theme +
    theme(panel.border=element_blank(), panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(), axis.line=element_blank())
  
  annotate_figure(p0, left = textGrob(y_labels, rot = 90, vjust = 1, gp = gpar(cex = 1.3)))
  
  # Arrange title on plots
  Yset <- ggarrange(p0, set, ncol=1, heights=c(0.07, 1))
  Yset_annotated <- annotate_figure(Yset,
                left = text_grob(y_labels, rot = 90, family = "Arial", size = 10))
  
  print(Yset_annotated)
  
  rm(plot_data)
  rm(p1, p4, p7, p0, Yset, Yset_annotated)
}

```



```{r VQ_Summary Barplot function}

plot_vq_barplot <- function(p, a, d, activity_label, depth_label, y_labels, parameter) {
  VQ_Summary <- as.data.frame(load_data_table(p, a, d, "VQSummary"))
  
  # Filter and subset dataframe for managed area
  ma_vq_summary <- VQ_Summary %>% filter(ManagedAreaName == ma)

  # VQSummary conditions for qualifying VQ values
  vq_condition <- ma_vq_summary$N_H !=0 | ma_vq_summary$N_I != 0 | ma_vq_summary$N_Q != 0 | ma_vq_summary$N_S != 0 | ma_vq_summary$N_U != 0
  
  # apply VQ_conditions to subset dataframe
  filtered_vq <- ma_vq_summary[vq_condition, ]
  
  # check to see if there are any qualifying VQ values, if not, skip
  if (nrow(filtered_vq) != 0) {
    # select respective perc_vq columns
    plot_data <- filtered_vq %>% 
      select(Year, N_Total, N_H, perc_H, N_I, perc_I, N_Q, perc_Q, N_S, perc_S, N_U, perc_U) %>%
      mutate_if(is.numeric, round, 2)
    
    # show only relevant columns for table display
    plot_data <- plot_data %>% 
      select(-where(~ all(. == 0)))

    # convert data format to "long" for plotting
    plot_data_long <- tidyr::pivot_longer(plot_data, 
                                          cols = starts_with("perc_"), 
                                          names_to = "Category", 
                                          values_to = "Percentage")
    
    # remove values when their VQ not included
    plot_data_long <- plot_data_long %>% 
      filter(Percentage != 0)
    
    # set year bounds for upper and lower
    year_lower <- min(plot_data_long$Year)
    year_upper <- max(plot_data_long$Year)
    
    # Use similar x-scaling to previous charts # may change
    x_scale <- ifelse(year_upper - year_lower > 30, 10, 
                      ifelse(year_upper == year_lower, 1, 3))
    
    # set title label
    lab_title <- paste0("Percentage Distribution of Value Qualifiers by year for ", d," Depths -  ", parameter)
    
    # plot results
    vq_plot <- ggplot(plot_data_long, aes(x=Year, y=Percentage, fill=Category)) + 
      geom_bar(stat = "identity", position="stack") +
      #geom_text(aes(label = ifelse(Category == "perc_H", N_H,
      #                       ifelse(Category == "perc_I", N_I,
      #                              ifelse(Category == "perc_Q", N_Q,
      #                                     ifelse(Category == "perc_S", N_S, N_U))))),
      #    position = position_dodge(width = 0.9),
      #    vjust = -0.1) +  # Adjust label position
      labs(title = lab_title,
           subtitle = paste(ma),
           x = "Year",
           y = "Percentage") +
      ylim(0, 100) +
      scale_x_continuous(limits=c(year_lower - 1, year_upper + 1),
                         breaks=rev(seq(year_upper,
                                        year_lower, -x_scale))) +
      scale_fill_manual(values=c("#00ADAE","#65CCB3","#AEE4C1","#FDE8A8","#F8CD6D"),
                        breaks=c("perc_H","perc_I","perc_Q","perc_S","perc_U"),
                        labels=c("H", "I", "Q", "S", "U")) +
      plot_theme
    
    vq_table <- ggtexttable(plot_data, theme=ttheme(base_size=10))
    
    vqSet <- ggarrange(vq_plot, vq_table, ncol=1)
    
    # print plots
    print(vqSet)
    
    # Add extra space at the end to prevent the next figure from being too
    # close.
    cat("\n \n \n")
    
    rm(VQ_Summary, filtered_vq, plot_data, plot_data_long, vq_plot)
  } else {
    cat(paste0("There are no qualifying Value Qualifiers for ", parameter, " in ", ma))
    cat("\n \n \n")
  }
}

```



```{r VQ-scatterplot}

plot_vq_Scatterplot <- function(p, a, d, activity_label, depth_label, y_labels, parameter, data) {
  
  data <- data %>% filter(!is.na(ValueQualifier)) %>% filter(ManagedAreaName == ma)
  
  if (nrow(data) != 0) {

    inc_H <- ifelse(p=="pH" | p=="DO" |
                  p=="DOS", TRUE, FALSE)
    
    if (inc_H==TRUE){
      # Remove any Value qualifiers that aren't H or U
      data$VQ_Plot <- gsub("[^HU]+", "", data$VQ_Plot)
      # Standardize order of qualifiers. Puts UH as HU
      data$VQ_Plot <- gsub("UH", "HU", data$VQ_Plot)
      # Remove anything from ValueQualifier that isn't U from programs and that
      # aren't ProgramID 476
      data$VQ_Plot[na.omit(data$ProgramID!=476)] <-
        gsub("[^U]+", "", data$VQ_Plot[na.omit(data$ProgramID!=476)])
      # Changes blank character strings to NA
      data$VQ_Plot[data$VQ_Plot==""] <- NA
      
      # If Parameter is Secchi_Depth
    } else if (p=="Secchi") {
      # Count the number of S ValueQualifier
      count_S <- length(grep("S", data$ValueQualifier))
      # Get percentage of S ValueQualifier
      perc_S <- 100*count_S/length(data$ValueQualifier)
      # Remove anything from ValueQualifier that isn't S or U
      data$VQ_Plot <- gsub("[^SU]+", "", data$VQ_Plot)
      # Change all ValueQualifier that are US to be US, standardizes codes
      data$VQ_Plot <- gsub("US", "SU", data$VQ_Plot)
      # Sets any blank character ValueQualifier to be NA
      data$VQ_Plot[data$VQ_Plot==""] <- NA
  
      # For all other scenarios
    } else{
      # Remove all ValueQualifier except U
      data$VQ_Plot <- gsub("[^U]+", "", data$VQ_Plot)
      # Sets any blank character ValueQualifier to be NA
      data$VQ_Plot[data$VQ_Plot==""] <- NA
      # Prints the number and percentage of I, Q, U
    }
    
    
    if(inc_H==TRUE){
      scale_fill <- c("H"= "#F8766D", "U"= "#00BFC4", "HU"="#7CAE00")
    } else if(p=="Secchi"){
      scale_fill <- c("S"= "#F8766D", "U"= "#00BFC4","SU"="#7CAE00")
    } else {
      scale_fill <- c("U"= "#00BFC4")
    }
    
    p1 <- ggplot(data=data[data$ManagedAreaName==ma&
                             data$Include==TRUE, ],
               aes(x=SampleDate, y=ResultValue, fill=ValueQualifier)) + #fill = VQ_Plot
      geom_point(shape=21, size=3, color="#333333", alpha=0.75) +
      labs(title=paste0(ma),
           subtitle=paste0("Qualified Values for ",parameter), x="Year",
           y=y_labels, fill="Value Qualifier") +
      plot_theme +
      theme(legend.position="top", legend.box="horizontal",
            legend.justification="right") +
      scale_fill_manual(values = scale_fill, na.value="#cccccc")
    
    print(p1)
    cat("\n \n \n")
  }
  
}

```



```{r dynamic_variables}
# Create conditions to determine if plots/text are shown
dynamic_vars <- list()
for (param in p_inc) {
  val <- ifelse(param %in% p_inc, TRUE, FALSE)
  assign(paste0("show_", param), val, envir = .GlobalEnv)
  dynamic_vars[[param]] <- get(paste0("show_",param))
}
```


```{r Plotting, warning=FALSE, fig.height=9, fig.width=10, results="asis"}

# Start looping for each parameter
for (param in p_inc) {
  
  data <- as.data.frame(load_data_table(param, table="data"))
  
  # getting full parameter & unit names
  parameter <- unique(data$ParameterName)
  unit <- unique(data$ParameterUnits)
  
  # defining labels for y-axis
  y_labels <- ifelse(param == "pH", parameter, paste0(parameter, " (" , unit, ")"))
  
  # Calling dynamic variables to create subtitles for each param
  if (get(paste0("show_", param))) {
    cat("\\newpage")
    subtitle <- glue("## {parameter}")
    cat(subtitle, "\n\n")
    cat("Parameter", parameter, "is included.\n\n")
  }
  
  #Because secchi depth is does not have a bottom measurement, this statement skips
  #Secchi depth for bottom
  if (param == "Secchi"){
    depth <- "Surface"
  } else {
    depth <- "All"
  }
  
  # Choosing which analyses to plot, when to combine 
  if (param == "ChlaC" |
      param == "Chla" |
      param == "CDOM" |
      param == "TN" |
      param == "TP") {activity = "Lab"} else if (
        param == "DO" |
        param == "DOS" |
        param == "pH" |
        param == "Secchi" |
        param == "TempW") {activity = "Field"} else if (
          param == "Sal" |
          param == "TSS" |
          param == "Turb") {activity = "All"}
    
  if (activity == "All") {
    activity_label <- "Lab and Field Combined"
  } else if (activity == "Field" | activity == "Lab") {
    activity_label <- activity
  }
  
  if (depth == "All") {
    depth_label <- "All Depths"
  } else if (depth == "Surface") {
    depth_label <- "Surface"
  }
  
  # Produce trendplots
  plot_trendlines(param, activity, depth, activity_label, depth_label, y_labels, parameter)

  # Produce boxplots
  plot_boxplots(param, activity, depth, activity_label, depth_label, y_labels, parameter, data)

  # Produce VQ-barplots
  plot_vq_barplot(param, activity, depth, activity_label, depth_label, y_labels, parameter)
  
  # Produce data-exclusion-tables
  data_exclusion_table(data, parameter)
  
  # Produce VQ-scatter-plots
  # plot_vq_Scatterplot(param, activity, depth, activity_label, depth_label, y_labels, parameter, data)
}

```


