

**Submerged aquatic vegetation** (*SAV*) refers to plants and plant-like macroalgae species that live entirely underwater. 
The two primary categories of *SAV* inhabiting Florida estuaries are *benthic macroalgae* and *seagrasses*. 
They often grow together in dense beds or meadows that carpet the seafloor. 
*Macroalgae* include multicellular species of green, red and brown algae that often live attached to the substrate by a holdfast. 
They tend to grow quickly and can tolerate relatively high nutrient levels, 
making them a threat to seagrasses and other benthic habitats in areas with poor water quality. 
In contrast, *seagrasses* are grass-like, vascular, flowering plants that are attached to the seafloor by extensive root systems. 
*Seagrasses* occur throughout the coastal areas of Florida, including protected bays and lagoons as well as deeper offshore waters on the continental shelf.
*Seagrasses* have taken advantage of the broad, shallow shelf and clear water to produce two of the most 
extensive seagrass beds anywhere in continental North America.  


## Parameters  


**Percent Cover** measures the fraction of an area of seafloor that is covered by SAV, 
usually estimated by evaluating multiple small areas of seafloor. 
Percent cover is often estimated for total SAV, individual types of vegetation (seagrass, attached algae, drift algae) and individual species.  

**Frequency of Occurrence** was calculated as the number of times a taxon was observed in a year divided by the number of sampling events,
multiplied by 100. Analysis is conducted at the quadrat level and is inclusive of all quadrats 
(i.e., quadrats evaluated using Braun-Blanquet, modified Braun-Blanquet, and percent cover."  


## Species  


**Turtle grass** (*Thalassia testudinum*) is the largest of the Florida seagrasses, with longer, thicker blades and deeper root structures
than any of the other seagrasses. It is considered a climax seagrass species.  

**Shoal grass** (*Halodule wrightii*) is an early colonizer of vegetated areas and usually grows in water too shallow for other species
except *widgeon grass*. It can often tolerate larger salinity ranges than other seagrass species. *Shoal grass* is characterized by thin, flat blades, 
that are narrower than *turtle grass* blades.  

**Manatee grass** (*Syringodium filiforme*) is easily recognizable because its leaves are thin and cylindrical instead of the flat, ribbon-like 
form shared by many other seagrass species. The leaves can grow up to half a meter in length. *Manatee grass* is usually found in mixed seagrass 
beds or small, dense monospecific patches.  

**Widgeon grass** (*Ruppia maritima*) grows in both fresh and salt water and is widely distributed throughout Florida's estuaries in less saline areas, 
particularly in inlets along the east coast. This species resembles *shoal grass* in certain environments but can be identified by the pointed tips 
of its leaves.  

Three species of *Halophila spp.* are found in Florida - **Star grass** (*Halophila engelmannii*), **Paddle grass** (*Halophila decipiens*), and 
**Johnson's seagrass** (*Halophila johnsonii*). These are smaller, more fragile seagrasses than other Florida species and are considered ephemeral. 
They grow along a single long rhizome, with short blades. These species are not well-studied, although surveys are underway to define their 
ecological roles.  


### Notes  


*Star grass*, *Paddle grass*, and *Johnson's seagrass* will be grouped together and listed as **Halophila spp.** in the following managed areas. 
This is because several surveys did not specify to the species level:  

* Banana River Aquatic Preserve  

* Indian River-Malabar to Vero Beach Aquatic Preserve  

* Indian River-Vero Beach to Ft. Pierce Aquatic Preserve  

* Jensen Beach to Jupiter Inlet Aquatic Preserve  

* Loxahatchee River-Lake Worth Creek Aquatic Preserve  

* Mosquito Lagoon Aquatic Preserve  

* Biscayne Bay Aquatic Preserve  

* Florida Keys National Marine Sanctuary  

